export const workerTypes = {
  SET_VACANCIES: "WORKER.SET_VACANCIES",
  SET_VACANCY: "WORKER.SET_VACANCY",
  SET_SELECT_VACANCY: "WORKER.SET_SELECT_VACANCY",
  SET_VACANCY_INFO: "WORKER.SET_VACANCY_INFO",
  SET_QUESTIONS_STEP: "WORKER.SET_QUESTIONS_STEP",
};
